### ISSUE TITLE
How to make connection through the kubernetes ingress?

### ISSUE THREAD

**Issue by Aracki** [crazy-max/docker-ejtserver#1]
I'm using this Docker image to run a pod inside a Kubernetes cluster. In this [stackoverflow post](https://stackoverflow.com/questions/55825585/is-there-a-way-to-make-ejtserver-talk-http) is said that before the version 1.13.1 it was possible to communicate with ejt-server through HTTP(s).

Any one managed to use ejt-license-server within a Kubernetes?

**Comment by crazy-max** [comment]
I'm not a k8s user but maybe you can use Traefik 2 as an ingress controller and use a [TCP router](https://docs.traefik.io/routing/routers/#configuring-tcp-routers)?

**Comment by Aracki** [comment]
This is not an option for me 🙁 Thanks anyways...

**Comment by Aracki** [comment]
The only way we have found to use it, was through service with type `LoadBalancer` and expose it there directly.
